### ISSUE TITLE
Feature Request: Validating model in request

### ISSUE THREAD

**Issue by MartynKeigher** [dfinke/PowerShellAI#10]
First off.. Thank you @dfinke for merging my PR yesterday for the paramter validation! Glad you found it useful! 

I would now like to extend the validation to also include the models, but.. i do not know how to incoproate it into the code. I have tried, but I just cant get it to work, so i'm hoping that with the following.. you can take it and incorporate it into your project. 

In code, you have:
```
...
...
    param(
        [Parameter(Mandatory)]
        $prompt,
        $model = 'text-davinci-003',
        [ValidateRange(0, 1)]
        [int]$temperature,
...
...
```

I want to change it to this, 
```
...
...
param(
        [Parameter(Mandatory)]
        $prompt,
        [ValidateSet($models)]
        [string]$model = 'text-davinci-003',
        [ValidateRange(0, 1)]
        [int]$temperature,
...
...
```
To get the possible values of `$models` for validating against, here is the API call I used to get the list...
```
$headers = @{
  "Content-Type" = "application/json"
  "Authorization" = "Bearer <OpenAI_API_TOKEN>"
}

$req = Invoke-WebRequest -Uri "https://api.openai.com/v1/models" -Method GET -Headers $headers
$models = $req | ConvertFrom-Json
$models.data.id | Sort-Object
```

By using this as your logic for your validation set, you are still using 'text-davinci-003' as your default, but you are expanding the response potential for the user, and again - with the validation - ensuring that the request that goes to OpenAI contains valid options - should they want to change the model from `text-davinci-003'.

Another benefit is that the Validation Set will always be up to date, as you're polling the source (OpenAI API) at the time of the request. There are 66 models today... and there is no sign of OpenAI slowing down any time soon! ;p

I have logged this here as an issue, so you have the code as my Powershell foo is off today, but I hope this gives you enough code\insipiration to work with! :) 

://mk

**Comment by dfinke** [comment]
Thanks. Yeah, I have a `Get-GPTModels`. I didn't implement as a dynamic param because of performance for now. I was thinking of "hardcoding" them but didn't want to be a bottleneck when they release new models.

A dynamic param makes sense once OpenAI, Microsoft and NVidia square away the offering.

**Comment by MartynKeigher** [comment]
Yeah, I'm not sure how (or even if its possible?) to make that API call, for models, be made **when you import the module**, and then the 'Get-GPT3Completion' has magic in it to reference the list? 
If it is possible, then i'm afraid to say that that is way above my Powershell punching weight! :(

**Comment by dfinke** [comment]
The `Invoke-WebRequest -Uri "https://api.openai.com/v1/models"` you have can be wired up to a "dynamic parameter".

Here's how I do it in my PSAdvantage module, but for files. https://github.com/dfinke/PSAdvantage/blob/3e91a816b7fc3191825829f5962f92edbd30f3fe/Public/Invoke-Advantage.ps1#L1
