### ISSUE TITLE
Cannot get AI function to work

### ISSUE THREAD

**Issue by HeyMrFrancis** [dfinke/PowerShellAI#103]
After reading and stepping through your install, I would like to see the AI function, but I cannot get it to work in my VSC  terminal.  I use you instructions and I receive the following errors:

ai 'list of planets only name as json'
Invoke-RestMethod: C:\Users\Administrator\Documents\PowerShell\Modules\PowerShellAI\0.5.3\Public\Invoke-OpenAIAPI.ps1:50:5
Line |
  50 |      Invoke-RestMethod @params
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~
     | 400 Bad Request
InvalidOperation: C:\Users\Administrator\Documents\PowerShell\Modules\PowerShellAI\0.5.3\Public\ai.ps1:44:9
Line |
  44 |          (Get-GPT3Completion -prompt $fullPrompt.Trim() -max_tokens $m …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

Same issue occurred with the Get-GPT3

PS C:\zDown\scripts\Sales\___AI\GIT\PowerShellAI-master\Public> Get-GPT3Completion "List of planets names only as json"
Invoke-RestMethod: C:\Users\Administrator\Documents\PowerShell\Modules\PowerShellAI\0.5.3\Public\Invoke-OpenAIAPI.ps1:50:5
Line |
  50 |      Invoke-RestMethod @params
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~
     | 400 Bad Request
PS C:\zDown\scripts\Sales\___AI\GIT\PowerShellAI-master\Public>

Please advise on how to correct - Thank you!
email - Frankadelbuono@gmail.com

**Comment by dfinke** [comment]
Have not seen that issue. That's an older version of the module. What version of PS and OS? Did you set your OpenAIKey?

**Comment by dfinke** [comment]
Were you able to get this to work?

**Comment by HeyMrFrancis** [comment]
Yes I have and I am all good.  Thank you!

**Comment by dfinke** [comment]
What was the issue?
