### ISSUE TITLE
copilot prompt doesn't match the answers

### ISSUE THREAD

**Issue by SP3269** [dfinke/PowerShellAI#104]
Here's an example of prompt generated by copilot:
```
What would you like to do?
[Y] Yes  [E] Explain  [N] No
```
`Yes` and `No` are not valid answers to the question.

## Proposed approach

Change the prompt to something like `Run the code? You can also choose additional actions`. That will make `Yes` and `No` valid responses while maintaining compatibility with the videos.

Add `Copy to clipboard` to the list of choices, and implement the functionality, to enrich the users' experience and elevate levels of happiness.

**Comment by SP3269** [comment]
Proposing PR to resolve ☝🏻

**Comment by dfinke** [comment]
Haha, thank you! Was top in my ToDo. Kept seeing that popup. Thanks for the clipboard. Will try.

Was thinking when choosing Run, it would inject it into history or PSReadline. Did not investigate. Need to guard maybe if someone is not using PSReadline.
