### ISSUE TITLE
Output showing HTML character codes OR just </code>

### ISSUE THREAD

**Issue by asheroto** [dfinke/PowerShellAI#122]
Perhaps this is an OpenAI issue, and not with PowerShellAI, but I wanted to bring it up to see what you think.

If I do this command...

```powershell
ai "list of planets only names as json, echo with php as array"
```

I get the output...

```php
<?php

$planets = array('Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune');

echo json_encode($planets);

?>
```

That is expected.

---

But if I do this command...

```powershell
ai "list of planets only names as json" | ai "echo with php as array"
```

I get this output...
```
</code>
```

---

And if I use this command...
```powershell
ai "list of planets only names" | ai "echo with php as array"
```

I get this output...
```
&lt;?php
$planets = array("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune");

echo implode(", ", $planets);
?&gt;</code>

Output: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune
```

Sometimes it shows `</code>`, sometimes it shows the longer version...

![image](https://user-images.githubusercontent.com/49938263/233952372-6fe5a573-cd95-484e-a5ea-0d6f57aeb3d4.png)

---

As you can see `</code>` is unexpected, and the HTML character codes like `&lt;` (less than) appear instead of `<`. But not always... Also in some examples, the output contains "Output: Mercury, Venus" etc. But not always... 😊

Not sure if this is an issue with OpenAI or with the module?

**PowerShellAI Version:** 0.6.0
**PowerShell Version**: 7.3.4

Thank you! 😊

**Comment by asheroto** [comment]
@dfinke gotcha, thanks for the info.

Does the code add any other information to the OpenAI API request? like... prefix it by saying "Perform the following, but as short as possible: <value from the prompt here>", or does it make a raw request?

Also, not related to this issue but I noticed the URLs in the repo are still pointing to beta.openai.com but now that it's out of beta the API path is https://platform.openai.com/account/api-keys

Thanks for your work on this!

**Comment by dfinke** [comment]
Thanks about the link. They need to be updated and do get redirected.

The `Get-GPT3Completion` is "raw", it is whatever you prompt.

`ai` and `copilot` are tuned a bit for PowerShell.

You could take the `ai` function and name it `myai` and then tweaked the prompt internally to better fit your needs.

**Comment by dfinke** [comment]
Update the `beta` links. Thank you!

**Comment by asheroto** [comment]
Thanks!
