### ISSUE TITLE
Get-DalleImage - "Billing hard limit has been reached"

### ISSUE THREAD

**Issue by AlexHimself** [dfinke/PowerShellAI#127]
The command `Get-DalleImage "A picture of a cat"` returns:

```
Invoke-RestMethod: C:\Program Files\PowerShell\Modules\PowerShellAI\0.6.1\Public\Invoke-OpenAIAPI.ps1:70:5
Line |
  70 |      Invoke-RestMethod @params
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~
     | {   "error": {     "code": "billing_hard_limit_reached",     "message": "Billing hard limit has been reached",     "param": null,     "type": "invalid_request_error"   } } 
Invoke-RestMethod: C:\Program Files\PowerShell\Modules\PowerShellAI\0.6.1\Public\Get-DalleImage.ps1:48:27
Line |
  48 |          Invoke-RestMethod $result.data.url -OutFile $DestinationPath
     |                            ~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
```

With this line appearing to indicate the problem:

> `"Billing hard limit has been reached"`

**Comment by dfinke** [comment]
That is an issue with your OpenAI account.

- Did you use all the initial credits, or did they expire?
- Did you add your credit card?
- Did you set a spending limit and reached it?

**Comment by AlexHimself** [comment]
I had no idea it was connected to my OpenAI account, so I must have used my initial credits. I had assumed it was still connected to a developer account or something. The ChatGPT functionality still works so I take it the credits must be different somehow.
