### ISSUE TITLE
Get-GPT3Completion return objects, not strings

### ISSUE THREAD

**Issue by StartAutomating** [dfinke/PowerShellAI#13]
This is one of those PowerShell core principles we all know and half-love.

Returning strings hides other information that might be useful, like:

1. What question did I ask?
2. When did I ask it?
3. What parameters were used?

Obviously, one doesn't want to display all of this inline.  This is why a separate issue will capture formatting and object requirements (see #14).

**Comment by dfinke** [comment]
Maybe. Need to flesh out more of the core concepts. Will revisit then.
