### ISSUE TITLE
Include a spinning wheel after `ai` command

### ISSUE THREAD

**Issue by StevenBucher98** [dfinke/PowerShellAI#135]
After I use the `ai` command it takes a while to return a response and the lack of "loading" indication makes me worry the command got hung. If there was some kind of progress wheel or spinning wheel. This node tool has a bunch of cool examples so take your pick! https://github.com/sindresorhus/cli-spinners

**Comment by dfinke** [comment]
Agreed! Thanks for the link. Also thinking of using spectre.console. 

https://github.com/dfinke/PowerShellAI/pull/94

There were issues with `Write-Progress` and the VS code console and PSReadline.
