### ISSUE TITLE
Progress bar fails in polyglot intereactive notebooks

### ISSUE THREAD

**Issue by dfinke** [dfinke/PowerShellAI#137]
@ShaunLawrie, ran into this.

I'm glad I did a walkthru of my presentation before I did it live. :-)

![image](https://github.com/dfinke/PowerShellAI/assets/67258/1cb08575-84dc-4419-88c9-281942626cf2)

**Comment by shaun-lawrie-ptml** [comment]
Smart move doing a test-run. I'll get it to fallback to no-progress in notebooks. That looks like jobs are unsupported in polyglot notebooks. I'll do a bit of digging
