### ISSUE TITLE
Formatting of GPT3 results

### ISSUE THREAD

**Issue by StartAutomating** [dfinke/PowerShellAI#14]
While we may want to be returning objects (#13), we don't want them to _look_ like raw objects.

To preserve existing behavior, the default formatter for GPT3 results should simply print the .Answer.

Additional functionality should be captured in additional views:

* A table view should display both the question and the answer, with word wrapping
* A list view should display the .`Question`, .`QuestionTime`, `.Answer`, .`AnswerTime`

Additional custom views should be able to display the question and answer with some colorization.

As this issue illustrates, we may also want to make the object returned from the REST api more convenient for users.

As such, we will also need to extend GPT-3 results.  This will be captured in another issue.

**Comment by dfinke** [comment]
Maybe. After fleshing out more, will revisit.
