### ISSUE TITLE
Convertfrom-GPTMarkdownTable - space in Noteproperty Name

### ISSUE THREAD

**Issue by ABrauser** [dfinke/PowerShellAI#141]
I noticed a bug in the "Converfrom-GPTMarkdownTable" it looks like that the trimming is not working correctly:

![image](https://github.com/dfinke/PowerShellAI/assets/41122078/9352acb6-42fd-4ecd-a6e1-4bd2e0586837)

Or is this issue only on my System?

**Comment by dfinke** [comment]
Looks like the
