### ISSUE TITLE
GPT fails when run from a PSDrive

### ISSUE THREAD

**Issue by jdhitsolutions** [dfinke/PowerShellAI#148]
It appears that you must run commands from a file system drive, and not a PSDrive. When I try to run a gpt command at a PSDrive, I get an error.

```powershell
 At C:\Program
Files\PowerShell\Modules\powershellai\0.7.5\Private\Invoke-RestMethodWithProgress.ps1:80 char:13
                       +             throw $job.ChildJobs[0].JobStateInfo.Reason
The background process reported an error with the following message: Remote transport error: Running startup script threw an error: Cannot find drive. A drive with the name 'S' does not exist...
```
My S: drive is mapped to C:\Scripts. When I change to C:\Scripts, the same command runs as expected.

**Comment by dfinke** [comment]
@ShaunLawrie thoughts?

**Comment by jdhitsolutions** [comment]
I've seen this before, and I think it is a quirk, or bug, with `Start-Job`. If I run `start-job {irm http://feeds.feedburner.com/PowerScripting}` from a mapped drive I get the error. Running the same command from C:\ works as expected. 

Further testing seems to indicate this is a PowerShell 7 issue.

**Comment by jdhitsolutions** [comment]
A hack like this sorta works.

```PowerShell
$here = Get-Location
if ($IsCoreCLR -AND ($here.ProviderPath -ne $here.path)) {
    Push-Location
    Set-Location $here.ProviderPath
    start-job {Invoke-RestMethod http://www.planetpowershell.com/feed}
    Pop-Location
} else {
    start-job {Invoke-RestMethod http://www.planetpowershell.com/feed}
}
```

What about using a thread job instead of Start-Job?

**Comment by ShaunLawrie** [comment]
Nice hack! I was supporting PowerShell 5 so I couldn't use threadjob.
