### ISSUE TITLE
Extending GPT3 Types

### ISSUE THREAD

**Issue by StartAutomating** [dfinke/PowerShellAI#15]
GPT3 RESTful return objects should be a made a lot easier to use.

There are a few major aspects of improvement:

* [x] `.Answer` should point to the first `.choices.text`
* [x] `.AnswerTime` should return the [DateTime] version of `.created` (which is a UNIX time)
* [x] `.ToString()` should output the .Answer

**Comment by dfinke** [comment]
KISS for now, will revisit
