### ISSUE TITLE
Command parameters should follow scripting standards

### ISSUE THREAD

**Issue by jdhitsolutions** [dfinke/PowerShellAI#150]
There are parameters in this module that should reflect scripting standards. A PowerShell parameter should have a clear and concise name using alphabetic characters only. The parameter should also be properly cased. For example, the parameter `top_p` should be something like `TopProbability`. The parameter `numberOfEdits` should be `NumberOfEdits`. This may seem like a small thing, but it makes the commands easier to read and use.

**Comment by dfinke** [comment]
I want to keep the names the same as the OpenAI reference implementation, so they are easier to look up. Their docs and processes are the Rosetta stone. Changing to `TopProbability` makes it difficult to find when searching for soultions.

**Comment by dfinke** [comment]
Somewhat agreed. Still too early to tell. This is not really an abstraction as it is a port of the Python implementation. 
The plan is once the "churn" settles down in the OpenAI SDK, it'll be easier to make those choices.

If, for example, you wanted to create your own `chat bot` using this. It is far easier to find and follow the OpenAI folks approach and mimic it with this approach.

The changes and innovations from the OpenAI side significantly changed just in the last six weeks. With ChatGPT plugins on the horizon, GPT-5. Keeping this aligned with their naming conventions is the only sane way to go.

**Comment by jdhitsolutions** [comment]
I wonder if this would make more sense if the module were written as a DSL instead of traditional functions.

**Comment by jdhitsolutions** [comment]
The more I use the module, the more I'm leaning toward describing it as a _framework_. It isn't a module like SMBShare where you can run commands without having to fully understand what is behind them. This module is something I would use to create my own tooling around AI services.  The `copilot` command is a good example. I would expect `copilot` to be user-friendly and serve as the abstraction to the underlying API-madness.

**Comment by jdhitsolutions** [comment]
Personally, I think this is an important topic that I'd recommend moving to Discussions and probably renaming. We're really getting into project goals and planning.

**Comment by dfinke** [comment]
Agreed. As a note, first pass at software development, make it work. 

I had no idea if GPT would get traction, much less this module.

Again, this can easily have an abstraction over it. This core will be needed for numerous other applications outside of DSLs, PowerShell naming standards etc.
