### ISSUE TITLE
Feature request: Add Set-OpenAIBaseRestURI

### ISSUE THREAD

**Issue by AjayKMehta** [dfinke/PowerShellAI#158]
First off, I love this module and appreciate you creating it, @dfinke!

I can't use it at work though because we have a wrapper around OpenAI due to security reasons and a different base URL.

Would it possible to add a cmdlet to change the base URL? I can add a PR this weekend if OK.

Thanks.

**Comment by dfinke** [comment]
Thanks @AjayKMehta glad you like. Agree on the feature request.

There is a `Set-AzureOpenAI` so you can go between Azure OAI and OpenAI.

I've been waiting for access to other LLMs via REST so I could come up with a clean way to switch, including having companies that do what your company does.

Maybe a `Set-OpenAIBaseRestURI` function is all that is needed. 

Please make a PR, add a few tests, let me know if you have questions and how it goes.

**Comment by dfinke** [comment]
Hi @AjayKMehta. The changes look good. I don't have workflows for creating pre-releases on GitHub and in the Gallery. Typically, I take the simplest path and push new releases. Setting up the pre-release will require more coordination on my end and I have not done those steps so I could introduce issues.

Also, I did not think this would have touched as much in the code. I need to think about it. I am also looking into other LLMs and their REST API setup. I do support the custom Azure OpenAI REST APIs.

More thinking on my part. 

It'll take some time, I have GPT presentations to prep for and more...

Thank you again.

**Comment by AjayKMehta** [comment]
Hi @dfinke, did you get a chance to review my PR further?

**Comment by dfinke** [comment]
Yes. Sorry, I thought I posted. I'm not going to merge. I had some issues trying different scenarios with this.

There are also things changing with Azure OAI and plan on re-visting it down the road.

Thanks again.
