### ISSUE TITLE
AI Functions not referencing PowerShell code and just referencing generic responses to given prompts

### ISSUE THREAD

**Issue by Xp101T7** [dfinke/PowerShellAI#162]
When I'm using the AI function exactly as the youtube video series you made suggests, its not creating powershell code based on the prompt that we are passing it, which is exactly how your Demo displays it.

When I pass the prompts it just gives me generic responses like 

```
 ai "how many processes are running with more than 700 handles"
It is not possible to answer this question without more information.
```

```
ai "# Check my IP?"
You can check your IP address by visiting a website such as https://www.whatismyip.com/.
```

```
ai "how many services are stopped?"
This depends on the specific system you are asking about. Generally speaking, you can use the command line to check the status of services on a system. For example, on Linux systems, you can use the command "systemctl list-units --state=inactive" to list all inactive services.
```

Any Idea how I can redirect this to prompt so I get the output as Code in the form of the Q/A table that displays the powershell command and asks me if I want to run it just like in your video series?

Also I'm using GPT-3.5-Turbo, still on the waitlist for 4.

**Comment by Xp101T7** [comment]
I just realized the Start-Demo might be why the Q/A tables are populating is this the case?

If so very cool, Ill dig in those docs. 

If not I still need to be able to pass the prompt to GPT as a PowerShell code reference to get the response as PowerShell functions.

**Comment by Xp101T7** [comment]
We can close this case now bc i just watched the next video series, [(908) PowerShell AI - copilot at the command line - YouTube](https://www.youtube.com/watch?v=JrNBvEm6E7Q&list=PL5uoqS92stXiW1xcAyMa7BMGgX-wdl_KV&index=6)
 , and co-Pilot does exactly what I was looking for. 
 
Should AI be able to do this?
Does Start-Demo to the Table Q/A view?

**Comment by dfinke** [comment]
Do which? the `ai` and `copilot` functions are tuned to do different things.

> Should AI be able to do this?

Could you say a bit more about this?
> Does Start-Demo to the Table Q/A view?
