### ISSUE TITLE
new-chat

### ISSUE THREAD

**Issue by bluehenve** [dfinke/PowerShellAI#163]
Hi Doug

I have started to get this issue:

![Clipboard](https://github.com/dfinke/PowerShellAI/assets/70111241/791ab5a1-6de7-4059-b08b-f2f410cd0880)

Regards, Henrik

**Comment by dfinke** [comment]
Thanks @bluehenve. I can repro the issue.

**Comment by dfinke** [comment]
This'll be a fun one :-)

For the tests I do not call out to the OpenAI backend, I mock it where needed, and don't mock errors.

I'll patch it and need to think through a strategy.

**Comment by dfinke** [comment]
@bluehenve fixed in v0.8.0. Thanks for posting the issue.
