### ISSUE TITLE
Can't do anyting

### ISSUE THREAD

**Issue by spidychoipro** [dfinke/PowerShellAI#167]
i use this command and i got this error
`PS C:\Users\swpar> gpt  can you tell me a joke?
Get-GPT3Completion: Cannot process argument transformation on parameter 'temperature'. Cannot convert value "tell" to type "System.Decimal". Error: "The input string 'tell' was not in a correct format."
PS C:\Users\swpar> gpt  "can you tell me a joke?"
Invoke-RestMethod: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}`

**Comment by dfinke** [comment]
## Try this

gpt ‘can you tell me a joke?’
