### ISSUE TITLE
invalid codepage in Get-GPT3Completion replies

### ISSUE THREAD

**Issue by swing-nn** [dfinke/PowerShellAI#177]
Facing an incorrect codepage in all responses when using Get-GPT3Completion with non-Latin based languages.
A similar issue was logged in https://github.com/dfinke/PowerShellAI/issues/3

When using Cyrillic in prompts, UTF-8 supposed, it is returning a response in Win-1252 codepage. 
__________
 an example below (questioned as 'a problem with encoding in gpt replies'):
```
PS > gpt "проблема с кодировкой в ответах gpt"
-2

ÐÑÐ¾Ð±Ð»ÐµÐ¼Ð° Ñ ÐºÐ¾Ð´Ð¸ÑÐ¾Ð²ÐºÐ¾Ð¹ Ð² Ð¾ÑÐ²ÐµÑÐ°Ñ GPT-2 Ð¼Ð¾Ð¶ÐµÑ Ð±ÑÑÑ Ð²ÑÐ·Ð²Ð°Ð½Ð° Ð½ÐµÑÐ¾Ð²Ð¼ÐµÑÑÐ¸
Ð¼Ð¾ÑÑÑÑ ÐºÐ¾Ð´Ð¸ÑÐ¾Ð²ÐºÐ¸ Ð¼ÐµÐ¶Ð´Ñ Ð¸ÑÑÐ¾Ð´Ð½ÑÐ¼Ð¸ Ð´Ð°Ð½Ð½ÑÐ¼Ð¸ Ð¸ Ð¼Ð¾Ð´ÐµÐ»ÑÑ GPT-2. ÐÐ»Ñ ÑÐµÑÐµÐ½Ð
¸Ñ ÑÑÐ¾Ð¹ Ð¿ÑÐ¾Ð±Ð»ÐµÐ¼Ñ Ð½ÐµÐ¾Ð±ÑÐ¾Ð´Ð¸Ð¼Ð¾ Ð¿ÑÐ¾Ð²ÐµÑÐ¸ÑÑ Ð¸ÑÑÐ¾Ð´Ð½ÑÐµ Ð´Ð°Ð½Ð½ÑÐµ Ð¸ Ð¼Ð¾Ð´ÐµÐ»Ñ GPT-
2 Ð½Ð° ÑÐ¾Ð²Ð¼ÐµÑÑÐ¸Ð¼Ð¾ÑÑÑ ÐºÐ¾Ð´Ð¸ÑÐ¾Ð²ÐºÐ¸ Ð¸ Ð¿ÑÐ¸ Ð½ÐµÐ¾Ð±ÑÐ¾Ð´Ð¸Ð¼Ð¾
```
______________

Expected result:
```
Проблема с кодировкой в ответах GPT-2 может быть вызвана несовмести
мостью кодировки между исходными данными и моделью GPT-2.
....
```
___________________

online decoder where I've verified results - 2cyr.com/decode/?lang=en
just FYI

**Comment by dfinke** [comment]
Thanks for reporting. 
Is this similar to https://github.com/dfinke/PowerShellAI/issues/62?

What version of PowerShell are you using?

**Comment by swing-nn** [comment]
Yes, https://github.com/dfinke/PowerShellAI/issues/62 seems the same. So, please close it as duplicating.
Meanwhile, I checked this in different PS versions and can confirm that encoding issue comes down to PS 5.1 only.

Both PS 7.4.0-preview4 under Windows  and PS 7.3.5 under Ubuntu display Get-GPT3Completion results properly.

Thank you
