### ISSUE TITLE
Unexpected error message when typing just `ai`

### ISSUE THREAD

**Issue by StevenBucher98** [dfinke/PowerShellAI#178]
I accidently hit enter before giving a prompt argument to the `ai` command and got back a weird response. It would be helpful to inform the user that they need to provide an argument that includes the users prompt or that they can pipe a prompt to it. Just a small bug I noticed and wanted to report. 
<img width="613" alt="Screenshot 2023-07-26 at 4 03 46 PM" src="https://github.com/dfinke/PowerShellAI/assets/20605456/36bb48c7-be1f-464c-a8b9-343ecbd53fc6">

**Comment by dfinke** [comment]
Thanks! Yes, adding parameter mandatory makes sense.
