### ISSUE TITLE
Get-OpenAIUsage

### ISSUE THREAD

**Issue by opustecnica** [dfinke/PowerShellAI#189]
Doug,

Thank you again for the module.

Do you know if there is a different way to get the OpenAI usage?  The Get-OpenAIUsage error hints at the function not being available via REST.

```
[CORE][me@computer:~]> Get-OpenAIUsage
Invoke-RestMethod: {
  "error": {
    "message": "Your request to GET /dashboard/billing/usage must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
Add-Member: C:\Users\me\Documents\PowerShell\Modules\PowershellAI\0.9.1\Public\Get-OpenAIUsage.ps1:34
Line |
  34 |      Add-Member -PassThru -MemberType NoteProperty -Name StartDate -Va …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.
```

Thank you

**Comment by dfinke** [comment]
I'll take a look. Used to work.

**Comment by dfinke** [comment]
Thanks for trying the PowerShellAI module.

Looks like they removed the endpoint from the Rest API.

https://platform.openai.com/docs/guides/production-best-practices/managing-costs

Easiest for me is to remove the function.

**Comment by opustecnica** [comment]
Makes total sense.  Thank you for looking into it.

**Comment by dfinke** [comment]
Thanks for raising the issue!
