### ISSUE TITLE
Export-JsonL

### ISSUE THREAD

**Issue by potatoqualitee** [dfinke/PowerShellAI#191]
Hey Doug,
Can you please add a command to convert a PowerShell object to JSONL? This is the format that OpenAI requires to train a model.

I'm trying to work your module into a book I'm writing and that'd be very helpful.

Seems pretty straightforward if this is true: https://github.com/rod-trent/OpenAISecurity/blob/main/PowerShell/JSON2JSONL.ps1

**Comment by potatoqualitee** [comment]
or like Out-JsonL? that two step blows

**Comment by dfinke** [comment]
Should be straight forward. I had done this when I was experimenting early on with fine tuning and thought not many folks would be interested.

Cool on the book and that you are looking to work the module in.

When do you need it by? I have some things on my plate.

Would the JsonL be enough for now? Or enabling the the fine tuning APIs are needed now for what you're doing?

**Comment by potatoqualitee** [comment]
Thank you! I'd say within 2 months would work. I actually don't know enough about it yet but part of the tutorial will be going on the website. It's less of a PS book and more of an AI book so I think that'll be all?

**Comment by potatoqualitee** [comment]
Oh, also, could there be an extension auto detector? like convert it from CSV or JSON based on .ext?

**Comment by potatoqualitee** [comment]
Hey Doug, in working through this, I realized that it's a little more involved than I expected. I want to include some binary parsers, so I'm going to make a dedicated modeling module and depend on yours. It'll be MIT so you can take anything and if the scope ends up being smaller than I thought and you're open to including DLLs, I'll PR  👍🏼

**Comment by dfinke** [comment]
Great! Binary parsers defintely make sense.

The core function I'm planning on is your first title ConvertTo-JsonL. You can pipe to it so you can send pscustomobjects, csv etc. If you piped json, it would need to convert it ConvetFrom-Json. I'll think about auto detecting or a switch.

Wiring up the fine-tuning was on my list, especiallly for Az Open AI. This module is configurable to work with both Rest APIs. Public and Azure.

**Comment by garbledhamster** [comment]
Hi Doug, Not an expert but I tried to do it manually but figured I'd see if you had an update on this.  With the new response_format options I was wondering if you could add this to the Set-ChatSessionOptions? To guarantee a well formatted json output from openai by default.

> response = openai.Completion.create(
>   model="text-davinci-003",
>   prompt="Translate the following English text to French: 'Hello, how are you?'",
>   **response_format={ "type": "json_object" }**
> )

Thank you!
