### ISSUE TITLE
ai command is throwing an error due to model text-davinci-003 deprecation

### ISSUE THREAD

**Issue by stevenjudd** [dfinke/PowerShellAI#204]
When running any commands using the `ai` command, I get the error "The model \u0060text-davinci-003\u0060 has been deprecated..." 

I get the same error using the `gpt` alias as well.

I'm running version 0.9.5

![image](https://github.com/dfinke/PowerShellAI/assets/19808166/92794891-492f-4478-a9f4-8166722f1a68)

**Comment by stevenjudd** [comment]
According to https://platform.openai.com/docs/deprecations/instructgpt-models this model was shut down on 2024-01-04.

**Comment by codypaternostro** [comment]
Both me and you are having the same problem at the same time!

**Comment by codypaternostro** [comment]
`PS C:\Users\Cody> $Error[3] | format-list * -Force

PSMessageDetails      :
OriginInfo            : localhost
Exception             : System.Management.Automation.RemoteException: Response status code does not indicate success: 404 (Not Found).
TargetObject          : Method: POST, RequestUri: 'https://api.openai.com/v1/completions', Version: 1.1, Content:
                        System.Net.Http.ByteArrayContent, Headers:
                        {
                          Authorization: Bearer ****lbWw
                          User-Agent: Mozilla/5.0
                          User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.22631; en-US)
                          User-Agent: PowerShell/7.4.0
                          Accept-Encoding: gzip
                          Accept-Encoding: deflate
                          Accept-Encoding: br
                          Content-Type: application/json
                          Content-Length: 232
                        }
CategoryInfo          : InvalidOperation: (Method: POST, Reque…tent-Length: 232
                        }:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
ErrorDetails          :
                        {
                          "error": {
                            "message": "The model \u0060text-davinci-003\u0060 has been deprecated, learn more here:
                        https://platform.openai.com/docs/deprecations",
                            "type": "invalid_request_error",
                            "param": null,
                            "code": "model_not_found"
                          }
                        }
InvocationInfo        :
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 3
PipelineIterationInfo : {}

PS C:\Users\Cody> $Error[4] | format-list * -Force

PSMessageDetails      :
OriginInfo            : localhost
Exception             : System.Management.Automation.RemoteException: Response status code does not indicate success: 404 (Not Found).
TargetObject          : Method: POST, RequestUri: 'https://api.openai.com/v1/chat/completions', Version: 1.1, Content:
                        System.Net.Http.ByteArrayContent, Headers:
                        {
                          Authorization: Bearer ****lbWw
                          User-Agent: Mozilla/5.0
                          User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.22631; en-US)
                          User-Agent: PowerShell/7.4.0
                          Accept-Encoding: gzip
                          Accept-Encoding: deflate
                          Accept-Encoding: br
                          Content-Type: application/json
                          Content-Length: 285
                        }
CategoryInfo          : InvalidOperation: (Method: POST, Reque…tent-Length: 285
                        }:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
ErrorDetails          :
                        {
                          "error": {
                            "message": "The model \u0060gpt-4\u0060 does not exist or you do not have access to it. Learn more:
                        https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.",
                            "type": "invalid_request_error",
                            "param": null,
                            "code": "model_not_found"
                          }
                        }
InvocationInfo        :
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 3
PipelineIterationInfo : {}
`

**Comment by Kriel** [comment]
I'm seeing the same issue. Just installed the cmdlet today.

The recency for all three of us suggests maybe something changed. Or, otherwise, there is a configuration step that isn't documented, or that we missed.

![image](https://github.com/dfinke/PowerShellAI/assets/7852718/bdb7b075-de01-4f94-a5db-e61ecc6f469f)

**Comment by dfinke** [comment]
Thank you @stevenjudd, @codypaternostro and @Kriel for using `PowerShellAI`.

Perfect timing, was sitting down to update the default model.

Thanks for logging the issue.

**Comment by dfinke** [comment]
Good news, bad news. I update  the model to `gpt-3.5-turbo-instruct`. It is trained differently. So the `ai` function responses are not optimal, you'd need to expand your prompts.

One option I can do is recode the `ai` function to use the new chat interface.
I already have `chat` which uses the conversational mode. It uses the `gpt-4` model. The trade-off is more accuracy, more cost and the accuracy makes it a bit slower.

You can experiment with different models like this.

Feedback welcome.

```
# Using a diff model gets verbose answers
Set-ChatSessionOption -model gpt-3.5-turbo

# you can prompt engineer that
#chat 'write a regex to find text that starts with OpenAI'
#chat 'write a regex to find text that starts with OpenAI, just the code'
chat 'write a regex to find text that starts with OpenAI, just the code, no explanation'
```

```powershell
<#
Get-OpenAIModel gpt*

gpt-4-0613
gpt-4
gpt-3.5-turbo-0301
gpt-3.5-turbo-16k-0613
gpt-3.5-turbo-instruct
gpt-3.5-turbo-16k
gpt-3.5-turbo-0613
gpt-3.5-turbo-instruct-0914
gpt-4-vision-preview
gpt-3.5-turbo
gpt-4-1106-preview
gpt-3.5-turbo-1106
gpt-4-0314

You can use any of these models with in chat mode.
#>


```

**Comment by stevenjudd** [comment]
@dfinke  I understood the `ai` command was using the API so it was pay for use. Does the `chat` command also use the API or do I need to have a subscription to OpenAI ChatGPT to use it? You probably answered this in one of your YouTube videos, so apologies for asking here. I am unclear on what the difference between using `ai` and `chat` would be.

Thanks for looking at and working on this. I use the `ai` command all the time and it not working has shown me just how much I use it and how valuable the module and functions you have written truly are.

**Comment by dfinke** [comment]
@stevenjudd Yes, the `ai` function is pay as you go. The `GPT model` I built it on `text-davinci-003` has these points:

- It uses the original `text-in` `text-out` completions. This has been moving to the new `chat` `message-in` `message-out` completions (also pay as you go).
- `text-davinci-003` has been deprecated. 
- The `ai` function was designed on the original `text-in` `text-out` completions. It would need to be upgrade to the `message-in` `message-out` completions.

Or you can use the `chat` function that does the `message-in` `message-out` completions, works as the pay for use.

The `chat` function does not support piping but has for flexibility for setting models etc. It may be more verbose.

I also just released https://github.com/dfinke/PowerShellAIAssistant. Uses the new features that OpenAI announced in November. This is the general direction as they deprecate models like `text-davinci-003` and others.

I'll be working up the `ai` and `copilot` functions to work with the new features. The new features go far beyond what these offer.

> This is about us paying the "innovation tax"

I suspect by June 2024, GPT-5 will drop and there will be new APIs, protocols etc.

The `ai` function is just a bit of a wrapper around the core OpenAI completion interaction.

Let me know your use cases. Do you only pass a prompt to the `ai` function or do you pipe things too etc.
I can either tweak the `chat` function or add a better `ai` in the new module.

**Comment by stevenjudd** [comment]
I was trying to understand the difference between the `ai` command and the `chat` command. I used `ai` and had never used the `chat` command until `ai` broke. I noted the output was different, and I was used to the output of the `ai` command. Not that the `chat` command output was bad, it was a bit more verbose than I was used to. I like the `ai` command better for the typing speed. 😉 

I'm embarrassed to say I didn't know you could pipe text to `ai`. 😬 I would give the context first, then ask the question:

`ai 'in wsl2, blah blah'` 
`ai 'in gitlab, blah blah'`

Or just ask it directly:

`ai 'what is the airspeed of a coconut-laden swallow'`

**Comment by dfinke** [comment]
Give https://github.com/dfinke/PowerShellAIAssistant a try. Now has `ai` and uses the same key.

You could alias `chat` to `ai`. Plus you can use `Set-ChatSessionOption -model gpt-3.5-turbo` so `chat` can use other models.

I have not found a good replacement `text-davinci-003`. 

I typically use `gpt-3.5` and `gpt-4` models and adjust my prompt.

The `PowerShell AI Assistant` uses the new Assistant config that stays in the cloud.

Absolutely worth learning. OpenAI  will continue in this direction.

**Comment by RStadlmair** [comment]
Having set the API key correctly, and 
`Set-ChatSessionOption -model gpt-3.5-turbo`
still produces the error. 
Where you you store/read that information, so i maybe can fix/set th there ?

PowerShellAI version 0.9.5 on macOS

**Comment by dfinke** [comment]
I suggest moving to using PowerShell AI Assistant

`Install-Module PowerShellAssistant -AllowClobber`

The above `Set-ChatSessionOption -model gpt-3.5-turbo` enables it for the `chat` function.

OpenAI is deprecating\stopping the model and the method (completion) that the `ai` function uses in the `PowerShellAI` module.

`PowerShellAssistant` is the way forward.

**Comment by AndrewPla** [comment]
For anyone else that stumbles across this, I believe the module that @dfinke is referring to is `PowerShellAIAssistant`

`Install-Module PowerShellAIAssistant -AllowClobber`

Checkout the repo here: https://github.com/dfinke/PowerShellAIAssistant

**Comment by blibdoolpoolp** [comment]
Definitely needs an announcement that this module is at least partially deprecated on the front page Doug! I was struggling with this for a couple weeks, then upon coming here to see if there were any additional updates I discovered this by chance. Looking forward to trying the new tool.

**Comment by lojones** [comment]
Perplexity ai led me to PowerShellAI, and i also struggled with getting it to work before I saw this note about it being effectively deprecated!

**Comment by dfinke** [comment]
@lojones Thanks for that note on Perplexity.

Head over to the new version. It is updated and using the new `OpenAI` API. `OpenAI` also marked their SDK as 1.0 so I'm betting this API will be around for a while.

https://github.com/dfinke/PowerShellAIAssistant
