### ISSUE TITLE
Doesnt seem to be using my api key?

### ISSUE THREAD

**Issue by J534** [dfinke/PowerShellAI#207]
After installing and importing the powershell module, as well as adding my OpenAIKey environment variable if I type ai "hello" I get the following error:
`Line |
  72 |      Invoke-OAIBeta -Uri $url -Method $Method -Body $body
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Incorrect API key provided: ''. You can find your API key at https://platform.openai.com/account/api-keys.
New-OAIThreadQuery: C:\Users\Justin\Documents\PowerShell\Modules\PowerShellAIAssistant\0.1.2\Public\Invoke-OAIChat.ps1:68
Line |
  68 |  … yResult = New-OAIThreadQuery -UserInput $prompt -Assistant $assistant
     |                                                               ~~~~~~~~~~
     | Cannot bind argument to parameter 'Assistant' because it is null.
InvalidOperation: C:\Users\Justin\Documents\PowerShell\Modules\PowerShellAIAssistant\0.1.2\Public\Invoke-OAIChat.ps1:71
Line |
  71 |          $messages.data[0].content.text.value
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.
Test-JsonReplacement: C:\Users\Justin\Documents\PowerShell\Modules\PowerShellAIAssistant\0.1.2\Private\Invoke-OAIBeta.ps1:80
Line |
  80 |          if (Test-JsonReplacement $message -ErrorAction SilentlyContin …
     |                                   ~~~~~~~~
     | Cannot bind argument to parameter 'JSON' because it is null.`

**Comment by dfinke** [comment]
Thanks for trying the module @J534.

Did you set your key like this `$env:OpenAIKey = 'sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'`

**Comment by Manbearpiet** [comment]
I have the same error, I had the environment variable set. I tried the `Set-OpenAIKey` but the same error:
`Script     0.1.5                 PowerShellAIAssistant               Desk`
```ps
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Darwin 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEAS…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```ps
ai "what is america it's favorite pizza"
Invoke-OAIBeta: /Users/christianpiet/.local/share/powershell/Modules/PowerShellAIAssistant/0.1.5/Public/New-OAIAssistant.ps1:72
Line |
  72 |      Invoke-OAIBeta -Uri $url -Method $Method -Body $body
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Incorrect API key provided: ''. You can find your API key at https://platform.openai.com/account/api-keys.
New-OAIThreadQuery: /Users/christianpiet/.local/share/powershell/Modules/PowerShellAIAssistant/0.1.5/Public/Invoke-OAIChat.ps1:68
Line |
  68 |  … yResult = New-OAIThreadQuery -UserInput $prompt -Assistant $assistant
     |                                                               ~~~~~~~~~~
     | Cannot bind argument to parameter 'Assistant' because it is null.
InvalidOperation: /Users/christianpiet/.local/share/powershell/Modules/PowerShellAIAssistant/0.1.5/Public/Invoke-OAIChat.ps1:71
Line |
  71 |          $messages.data[0].content.text.value
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.
Invoke-OAIBeta: /Users/christianpiet/.local/share/powershell/Modules/PowerShellAIAssistant/0.1.5/Public/Remove-OAIAssistant.ps1:30
Line |
  30 |          Invoke-OAIBeta -Uri $url -Method $Method
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [https://api.openai.com/v1/assistants/] - Cannot follow an insecure redirection by default. Reissue the command specifying the
     | -AllowInsecureRedirect switch.
     ```

**Comment by dfinke** [comment]
`Set-OpenAIKey` is for the older module `PowerShellAI`

Without sharing your key, pls past how you are setting the environment variable.

**Comment by NETvide** [comment]
I'm seeing a similar problem using your sanity-check code

PS C:\Temp> .\sanity-check.ps1
Invoke-OAIBeta: C:\Users\jconstan\Documents\PowerShell\Modules\PowerShellAIAssistant\0.1.6\Public\New-OAIAssistant.ps1:72
Line |
  72 |      Invoke-OAIBeta -Uri $url -Method $Method -Body $body
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Incorrect API key provided: ''. You can find your API key at https://platform.openai.com/account/api-keys.
Invoke-OAIBeta: C:\Users\jconstan\Documents\PowerShell\Modules\PowerShellAIAssistant\0.1.6\Public\Remove-OAIAssistant.ps1:30
Line |
  30 |          Invoke-OAIBeta -Uri $url -Method $Method
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [https://api.openai.com/v1/assistants/] - Cannot follow an insecure redirection by default. Reissue the command
     | specifying the -AllowInsecureRedirect switch.
PS C:\Temp> .\sanity-check.ps1
Invoke-OAIBeta: C:\Users\jconstan\Documents\PowerShell\Modules\PowerShellAIAssistant\0.1.6\Public\New-OAIAssistant.ps1:72
Line |
  72 |      Invoke-OAIBeta -Uri $url -Method $Method -Body $body
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Incorrect API key provided: ''. You can find your API key at https://platform.openai.com/account/api-keys.
Invoke-OAIBeta: C:\Users\jconstan\Documents\PowerShell\Modules\PowerShellAIAssistant\0.1.6\Public\Remove-OAIAssistant.ps1:30
Line |
  30 |          Invoke-OAIBeta -Uri $url -Method $Method
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [https://api.openai.com/v1/assistants/] - Cannot follow an insecure redirection by default. Reissue the command
     | specifying the -AllowInsecureRedirect switch.

On this version of PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by NETvide** [comment]
Exactly as shown in the commented out section of Sanity-CheckOn 2 Feb 2024, at 00:27, Doug Finke ***@***.***> wrote:﻿
@NETvide how are you setting your key in the environment? $env:OpenAIKey?
