### ISSUE TITLE
Get-DalleImage only works with OpenAI not Azure Open AI

### ISSUE THREAD

**Issue by darrenjrobinson** [dfinke/PowerShellAI#208]
Get-DalleImage doesn't work for Azure Open AI. 
I tried to quickly make modifications to the cmdlet to allow switching like other cmdlets but there are many inter-cmdlet dependencies. 

@dfinke  Would you like a PR with a NEW cmdlet specifically for Azure OpenAI or an update to the existing one?

**Comment by darrenjrobinson** [comment]
Over changes to Get-DalleImage the key script with bigger changes is Invoke-OpenAIAPI which then flows on to Invoke-RestMethodWithProgress and then I stopped. 
Will do a new cmdlet. 
Any pref on name of the cmdlet?
Get-DalleImageAzureOpenAI ??

**Comment by dfinke** [comment]
I would swap `Get-AzureOpenAIDalleImage` maybe `Get-AOAIDalleImage`
