### ISSUE TITLE
Question about UTF-8 encoding and response length

### ISSUE THREAD

**Issue by dfinke** [dfinke/PowerShellAI#3]
### Discussed in https://github.com/dfinke/PowerShellAI/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **Painkiller8818** January 14, 2023</sup>
Hi,

i tried your module and i like it a lot, but what i found is when i send german questions, the response seems not to be UTF-8.

This is a bit strange because in your Get-GPT3Completion.ps1 i can see you are converting it to UTF-8BOM.

Any way to force the response also to be UTF-8?

Another question is the response length.

Sometimes i don't get the full response, it cuts the text somewhere in the middle of a text.
Does this has to do with the maxtokens? i am not really sure if this is what i am looking for.

Any ideas how to increase the response length? 

Thanks a lot
</div>

**Comment by dfinke** [comment]
`-max_tokens 512` can be used for example. I believe it is a max of 4k. That number includes what you send plus what is returned.

Could you post an example of what you are doing so I can see what the issue is and then we can go from there.

**Comment by MartynKeigher** [comment]
If the response is "cut short", then you can follow up the response with `Get-GPT3Completion 'continue'` and it will spit out the remainder\next chunk of the response until the max_token is reached again. 
Just note that the higher you set your max_token, the longer you will be waiting for the response. ;p

**Comment by MartynKeigher** [comment]
After thinking about the 'delay' while we wait for the response, I made a PR for it. 

https://github.com/dfinke/PowerShellAI/pull/7

**Comment by dfinke** [comment]
@MartynKeigher Thanks for the PR! I've been thinking about/reviewing ways to do this. I'll check out what you add.

**Comment by MartynKeigher** [comment]
No problems! Was fairly simple. I’m sure there are more elaborate ways to do it, but I figured it was a good starter!
