### ISSUE TITLE
Many commands lack complete help

### ISSUE THREAD

**Issue by StartAutomating** [dfinke/PowerShellAI#56]
A number of the commands in PowerShellAI lack complete Inline help (many lack a `.DESCRIPTION`, some lack parameter help)

I'm creating this issue to track housekeeping of code, and will fix what I can quickly.

* [x] ConvertFrom-GPTMarkDownTable - Lacks description.  Example's use of heredocs makes copying/pasting to terminal not work.
* [x] Disable/Enable-AIShortCutKey Lack Description and .LINK
* [x] Get-OpenAIBaseRestUR - Lack Description and .LINK, Example incorrect
* [x] Get-OpenAICompletionsURI Lack Description, .LINK, and Examples
* [x] Get-OpenAIEditsURI - Lack Description, .LINK, and Examples 
* [x] Get-OpenAIImagesGenerationsURI - Lack Description, .LINK, and examples
* [x] Get-OpenAIModelsURI - Lack Description, .LINK, and examples
* [x] Get-OpenAIModeration - `Raw` Parameter Undocumented
* [x] Get-OpenAIModerationsURI - Lack Description, .SYNOPSIS, .LINK, .Examples
* [x] Set-DalleImageAsWallPaper - Lacks Description, Parameters Undocumented, Should note Windows only
* [x] Set-OpenAIKey - Lacks Links

**Comment by dfinke** [comment]
will review down the road
