### ISSUE TITLE
Encoding issues for different languages than English (only in PowerShell 5.1)

### ISSUE THREAD

**Issue by laheller** [dfinke/PowerShellAI#62]
Hi @dfinke 

When I ask a question from ChatGPT in a different language than English, the answer however is displayed but with incorrect character encoding. See the example screenshot below:
![image](https://user-images.githubusercontent.com/5788998/222213866-dfa0abef-e909-4561-ba60-255dd56e9d03.png)

I simply asked in hungarian language "Mennyi hat meg hat?" = "How much is six plus six?"
The answer is correct, but it should be "Hat meg hat egyenlő tizenkettő."

So my question is, whether this is a module issue or just a whatever Windows setting?
What I tried is to set the output encoding in PowerShell console to various encodings, like for example:
`[console]::OutputEncoding = [System.Text.Encoding]::UTF8
`
but unfortunately none of them helped.

BR,

Ladislav

**Comment by dfinke** [comment]
Sounds like this is a PowerShellAI issues. I need to look into it.

**Comment by laheller** [comment]
Hi @dfinke !

Any update on this issue?

BR,

Ladislav

**Comment by dfinke** [comment]
@laheller sorry. Unfortunately, it works for me. I made no changes to the code. I don't remember customizing my windows terminal.

![image](https://user-images.githubusercontent.com/67258/226101412-2b985d2e-cbb8-4fed-840f-6ede07c3371f.png)

**Comment by insjs** [comment]
@laheller @dfinke I think the behavior is different for PS and PS7 
![image](https://user-images.githubusercontent.com/118421898/226828750-6acd7da9-5cf7-4a93-b52d-c7c6379f5e71.png)

**Comment by laheller** [comment]
@insjs @dfinke 

I forgot to mention that I am using PowerShell 5.1

**Comment by dfinke** [comment]
Hmm, tried 5.1 in windows terminal. Printed ok

**Comment by laheller** [comment]
Hi @dfinke @insjs 

There is something definitely on the client side (at the PS module), because the server response encoding through http proxy monitor is correct:
![image](https://user-images.githubusercontent.com/5788998/228511778-d5309234-4c9d-4fd3-9f7c-cfe4b976ee22.png)

**Comment by dfinke** [comment]
I talked with someone and they said the ASCII set on does not have two characters needed for the Hungarian language. I don't know how or why I seem to have it, but it works

**Comment by laheller** [comment]
> I talked with someone and they said the ASCII set on does not have two characters needed for the Hungarian language. I don't know how or why I seem to have it, but it works

@dfinke is the server response encoding translated to ASCII by PowerShellAI module? Why?

**Comment by laheller** [comment]
@dfinke  @insjs 

Found a workaround for PowerShell 5.1, basically we have to interpret the raw result as an ISO-8859-1 encoded text, then translate it to UTF8:
```
$raw   = Get-GPT3Completion -prompt 'Mennyi hat meg hat?' -Raw -Verbose
$text  = $raw.choices[0].text
$bytes = [System.Text.Encoding]::GetEncoding('iso-8859-1').GetBytes($text)
[System.Text.Encoding]::UTF8.GetString($bytes)

```
Using the above the result is displayed correctly!

**Comment by dfinke** [comment]
Thanks, that's great!

- Wonder why it works on my installation?
- Wonder if I add that to the module it will work across the boards?

**Comment by laheller** [comment]
> Good idea. Still don't know why my set-up works, I'm using PS v7.3.1 and Windows Terminal. I'd prefer not to add more parameters. Plus supporting encodings opens it up to lots of questions.

@dfinke  I would try it on another machine and PowerShell_5.1. In my case I reproduced it on 3 different machines.
As I wrote above, in PS7.3 also works for me correctly! Therefore I also changed the title of issue.
