### ISSUE TITLE
Naming collision in Get-OpenAIKey causes private function to be exported

### ISSUE THREAD

**Issue by ShaunLawrie** [dfinke/PowerShellAI#73]
Running `Get-OpenAIKey` should list your keys using the function in [Public/Get-OpenAIKey.ps1](https://github.com/dfinke/PowerShellAI/blob/master/Public/Get-OpenAIKey.ps1)

But the function in [Private/Get-OpenAIKey.ps1](https://github.com/dfinke/PowerShellAI/blob/master/Private/Get-OpenAIKey.ps1) runs instead.

![image](https://user-images.githubusercontent.com/13159458/223962126-9d2d026a-4b4c-4142-a713-07d8c4c50027.png)

**Comment by dfinke** [comment]
@ShaunLawrie thanks for posting that. Resolved https://github.com/dfinke/PowerShellAI/pull/74
