### ISSUE TITLE
`Get-ChatInProgress` - Add ID Column

### ISSUE THREAD

**Issue by mattcargile** [dfinke/PowerShellAI#79]
Been playing with `New-Chat`, etc. 

I was a bit confused about the `role`  and `content` output. I feel like there could be a better header than `role` but once I got it then it made sense.

Additionally, it would be nice to add an ID to the output. Maybe using the `RefId` in the `xml`?

**Comment by dfinke** [comment]
Thanks! I kept the role and content from the OpenAI api. When this gets documented I’ll point to their description. 

What scenario do you see for the Id?

**Comment by mattcargile** [comment]
I guess general sorting if I had a long convo and I wanted to return the last item first. 

```powershell
get-chatinprogress | sort id -desc | select -first 2
```

I could workaround with `select -last 2` so maybe it isn't necessary. 

Additionally, it does make me feel a bit better to see the IDs so I know it is in order but that is just a preference. :-)

**Comment by mattcargile** [comment]
Alright. Yeah I guess just documentation on the order or just close it out. I don't have anything very substantive.

In general, it is just nice to have a "primary key" for reference. My only example now is to be able to do `get-chatinprogress | sort id -desc | select -first 2` instead of using `-Last`.

**Comment by dfinke** [comment]
Great, appreciate the feedback.

Don't want to build this in a bubble. 🙂
