### ISSUE TITLE
Questions are Split by the answer based on cursor position

### ISSUE THREAD

**Issue by ninmonkey** [dfinke/PowerShellAI#8]
## Problem

When cursor isn't at the end of the comment, it gets pushed to the end -- after the response ends.  (Or, maybe it's intended behavior?)

A low cost fix could check if the final AST element is a comment, and the cursor isn't at the end, move to the end before pasting.

```ps1
# replace for loop with<cursor> range operator
```

## Input was
```ps1
# replace for loop with range operator
```
![image](https://user-images.githubusercontent.com/3892031/212827555-330411f1-da53-489f-b3ee-bc8684634aee.png)

## Output
```ps1
 # replace for loop with


 $collection = [System.Collections.Generic.List[int]]::new()
 128..132 | ForEach-Object {
     $collection.Add((Get-Random -Minimum $_ -Maximum ($_ + 4)))
 } range operator
```

![image](https://user-images.githubusercontent.com/3892031/212827596-fb8d279e-ed7e-4e18-9771-57e04c0c2563.png)

## Full Session Dump

```ps1
Ps7┐ # array of 200 numbers between 128 and 132
|
|
| $array = 128..132 | Get-Random -Count 200
| # choose random numbers without piping to get-random
| $array = @()
| for ($i=0; $i -lt 200; $i++) {
|     $array += Get-Random -Minimum 128 -Maximum 132
| }
| # use generic collections instead of array
|
| $collection = [System.Collections.Generic.List[int]]::new()
| for ($i=0; $i -lt 200; $i++) {
|     $collection.Add((Get-Random -Minimum 128 -Maximum 132))
| }
| # replace for loop with
|
|
| $collection = [System.Collections.Generic.List[int]]::new()
| 128..132 | ForEach-Object {
|     $collection.Add((Get-Random -Minimum $_ -Maximum ($_ + 4)))
| } range operator
```

**Comment by dfinke** [comment]
Looking at other solutions to this. Potentially a different function with different capabilities.
