### ISSUE TITLE
`Invoke-AIExplain` - Add More Prompt Context

### ISSUE THREAD

**Issue by mattcargile** [dfinke/PowerShellAI#80]
It would be nice if this line maybe had a little more "code" type context added instead of only `'explain'`.

https://github.com/dfinke/PowerShellAI/blob/4adb4c2e9be91ffaf39bb70dce2f4a534f1b1561/Public/Invoke-AIExplain.ps1#L31

Code like `'gcm -mo *ai' | ai 'explain'` fail and return information about Google. 

```powershell
'gcm -mo *ai' | ai 'explain powershell code'
```
Code above works a little better, but it still misses the shortened parameter. Maybe _GPT-4_ is better. :-)

I played with a bit more. The below _boxed_ items worked well.
![image](https://user-images.githubusercontent.com/74641867/225471071-e8f4d548-83f3-441b-9dc9-dae3c4076e3e.png)

**Comment by dfinke** [comment]
Good point. Was running into that. I think I may add a $prompt parameter. That way you can add “powershell code“ or “bash” etc

**Comment by mattcargile** [comment]
I was considering a few switches for different shells? It would be nice if `explain` could grab the current "shell" ( i.e. `cmd`, or `pwsh` or `powershell` or `bash` ) and craft the "right" prompt by default.

**Comment by dfinke** [comment]
Check out my PR for this. Experimenting with pulling info from $PSVersiontable.

**Comment by mattcargile** [comment]
Hmm. Interesting. I probably would be better to shoot for a platform versus trying to tackle shell versions. It would be challenging to separate code passed in that uses "cmdlets" versus application without using `PSParser` or the like to see if the user is using an application or not. 

Not sure what version you want to target. I don't have `$PSVersionTable.Platform` on _5.1_. I could definitely see forcing a _Core_ version dependency. I did think it would be good to try to combine _Desktop_ and _Core_ into one prompt. I think it might be hard for the AI to separate those versions assuming you wanted to support _Desktop_.

**Comment by dfinke** [comment]
Yes. Going to add more than the `Platform` and experiment.

The more that is added the slower the `explain`.

Need to figure out the balance between accuracy and speed.

Also may add a `$prompt` param and you can create your own prompt.

**Comment by dfinke** [comment]
Merged https://github.com/dfinke/PowerShellAI/pull/81

@mattcargile Thanks for the feedback and input!
