### ISSUE TITLE
Get-ChatCompletion.ps1 Configure $max_tokens

### ISSUE THREAD

**Issue by johanvts** [dfinke/PowerShellAI#82]
This script works really well, thank you! But I can't figure out how to configure max tokens. It would be great if it was accessible on a per chat basis. Same with the temperature. So you could do:

> chat "Try to write a long story about birds" -max_tokens 2000 -temperature 1
> chat "what is 2 + 2?" -max_tokens 10 -temperature 0

**Comment by dfinke** [comment]
Thanks for the issue!

The `chat` -> `Invoke-ChatCompletion` doesn't have those parameters wired in to work at the cli, yet.

The intention is for this to be use at the cli and in a script. I am thinking through having a `chat config` file.

Will probably end up supporting both.

Working on refactoring this. I wanted to publish it for feedback etc.

**Comment by johanvts** [comment]
I understand, looking forward to a refactored version :) One more thing is that when you pass the prompt through as a parameter you can use variables like this:
```
chat "improve $this"
```
which doesn't work in when you use Read-Host, ex. 
``` 
'> Please tell me what you would like to know "improve $this"'
```
Doesn't get `$this` expanded.

**Comment by dfinke** [comment]
Could you say a bit more about the `chat "improve $this"`

**Comment by johanvts** [comment]
I use it to pass longer text to the chat. For example
````
> $method = @"
public void MyMethod()
{
//this method needs work
}
"@
> chat "improve $method"
```

**Comment by dfinke** [comment]
Got it! TIL :-)  I've never tried to pass a $var to a `Read-Host`. Will investigate.
