### ISSUE TITLE
Pester tests have issues if module is installed and clears the API key

### ISSUE THREAD

**Issue by dfinke** [dfinke/PowerShellAI#84]
Hi @kborowinski. Two issues:

1. If I have the module installed and run the tests I get the error below. I use https://github.com/dfinke/PowerShellAI/blob/master/InstallModule.ps1
2. After running the tests, it clears out the `$env:OpenAIKey` so I have to `. $PROFILE` so I can use the functions

Please can you take a look a rework so the tests can be run locally and still leave the environment as it was?
Thank you.

![image](https://user-images.githubusercontent.com/67258/226168884-1bce8e2d-d6d1-406e-9e25-523da56e3735.png)

![image](https://user-images.githubusercontent.com/67258/226168907-8acc1913-d715-4a6e-a6dd-d6b5f8b42e9a.png)

**Comment by kborowinski** [comment]
I'll have a look as soon as I'm back from TDY (early next week).

**Comment by dfinke** [comment]
No rush

**Comment by kborowinski** [comment]
@dfinke I think that you can close this now
