### ISSUE TITLE
Get-ChatCompletion.ps1 throws error when importing PowerShellAI module

### ISSUE THREAD

**Issue by ztrhgf** [dfinke/PowerShellAI#89]
When importing new 0.5.3 module version error is thrown 
![image](https://user-images.githubusercontent.com/2930419/226613758-6a96dc69-1630-4c89-a7b5-b2a33a894854.png)

Problem seems to be in 0.5.3\Public\Get-ChatCompletion.ps1 where because of missing $IsWindows variable, $env:HOME is used in Join-Path command which fails 
![image](https://user-images.githubusercontent.com/2930419/226614080-4a6e3ff9-e613-4978-b6e0-674c977a8df5.png)

**Comment by dfinke** [comment]
Thanks @ztrhgf! What version of PowerShell are you using? `$PSVersionTable`

**Comment by ztrhgf** [comment]
![image](https://user-images.githubusercontent.com/2930419/226615333-ba8b6481-6133-462c-8fe7-1796a15329be.png)

**Comment by dfinke** [comment]
@kborowinski could you check this out? Probably a `$PSVersionTable.PSEdition` check?

**Comment by kborowinski** [comment]
Yep, it will throw in `StrictMode` on PS5 and lower. Will make a PR later today

**Comment by dfinke** [comment]
Thank you 🙏

**Comment by dfinke** [comment]
Going to release a new version of this an will incorporate @kborowinski fix in that.
