### ISSUE TITLE
[UX] A Visual Notification to Let the User Know a Query is In Progress

### ISSUE THREAD

**Issue by ninmonkey** [dfinke/PowerShellAI#9]
A tiny visual notification that a query is running would be nice. Sometimes it's hard to tell if a `ctrl+g` query fired or not.

If a spinner is not simple, drawing a single dot when firing the query would be good enough.

**Comment by MartynKeigher** [comment]
I have submitted a PR (https://github.com/dfinke/PowerShellAI/pull/6) for exactly this... it's currently with @dfinke.
