### ISSUE TITLE
Module import issue with latest 0.5.4 version

### ISSUE THREAD

**Issue by KurtDeGreeff** [dfinke/PowerShellAI#93]
import-module powershellai
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\powershellai\0.5.4\Public\Get-ChatCompletion.ps1:38 char:41
+     $Script:chatSessionPath = Join-Path $env:HOME '~/PowerShellAI/Cha ...
+                                         ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

I don't have $env:HOME ..

**Comment by KurtDeGreeff** [comment]
It's because I'm still using Windows Powershell at work. $IsWindows is not available here

**Comment by dfinke** [comment]
Thank you for reporting. I am refactoring that. The next version will handle v5.1 correctly.
