### ISSUE TITLE
$path and $file error when using Invoke-ChatCompletion

### ISSUE THREAD

**Issue by PiotreksWorld** [dfinke/PowerShellAI#97]
I get this error using the command mentioned. Any idea how to solve it?

Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\user123\Dokumente\WindowsPowerShell\Modules\PowerShellAI\0.5.4\Public\Get-ChatCompletion.ps1:124 char:23
+     $file = Join-Path $Script:chatSessionPath ("{0}-ChatGPTSession.xm ...
+                       ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCom
   mand

Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\user123\Dokumente\WindowsPowerShell\Modules\PowerShellAI\0.5.4\Public\Get-ChatCompletion.ps1:126 char:25
+     if (-not (Test-Path $Script:chatSessionPath)) {
+                         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom
   mand

Export-Clixml : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\user123\Dokumente\WindowsPowerShell\Modules\PowerShellAI\0.5.4\Public\Get-ChatCompletion.ps1:130 char:44
+     $Script:messages | Export-Clixml -Path $file -Force
+                                            ~~~~~
    + CategoryInfo          : InvalidData: (:) [Export-Clixml], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ExportClixm
   lCommand

Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\user123\Dokumente\WindowsPowerShell\Modules\PowerShellAI\0.5.4\Public\Get-ChatCompletion.ps1:124 char:23
+     $file = Join-Path $Script:chatSessionPath ("{0}-ChatGPTSession.xm ...
+                       ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCom
   mand

Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\user123\Dokumente\WindowsPowerShell\Modules\PowerShellAI\0.5.4\Public\Get-ChatCompletion.ps1:126 char:25
+     if (-not (Test-Path $Script:chatSessionPath)) {
+                         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom
   mand

Export-Clixml : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\user123\Dokumente\WindowsPowerShell\Modules\PowerShellAI\0.5.4\Public\Get-ChatCompletion.ps1:130 char:44
+     $Script:messages | Export-Clixml -Path $file -Force
+                                            ~~~~~
    + CategoryInfo          : InvalidData: (:) [Export-Clixml], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ExportClixm
   lCommand

**Comment by dfinke** [comment]
Thank you. What version of PowerShell are you using, v5.1?

**Comment by PiotreksWorld** [comment]
Yes, PS Version 5.1.22621.963

**Comment by dfinke** [comment]
I've got an update coming out that addresses this

**Comment by PiotreksWorld** [comment]
Lightning-fast support, thanks a lot, I really appreciate your awesome work! Have lovely day, greetings from Germany!

**Comment by dfinke** [comment]
Please try the latest version
